### ISSUE TITLE
[feature request]Support performance mode, Proxify only first level children

### ISSUE THREAD

**Issue by zxdong262** [tylerlong/subx#2]
Possible use case is converting old code to use subx, or user would like to always set first class children only to gain better performace.

**Comment by zxdong262** [comment]
Like this: https://github.com/electerm/subx/blob/dev/src/index.js#L17

**Comment by tylerlong** [comment]
It's a good idea. I might add `recursive: false` support later.

**Comment by tylerlong** [comment]
Done. doc: https://github.com/tylerlong/subx#recursive
